repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.35.2
    hooks:
      - id: typos

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.8
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
